### ISSUE TITLE
prerequisite tools should be installed from script.sh

### ISSUE THREAD

**Issue by AvineshTripathi** [kubeslice/examples#23] opened 2022-07-22 11:38 UTC
When checking for required tools if any tool is missing the script throws an error as shown 
![2022-07-22_16-47](https://user-images.githubusercontent.com/73980067/180429820-8b3baf1f-16bd-48f9-a58a-553c8ad80112.png)

the question here is should we install the missing tool instead

there is another question to follow up that is if we install the tools are we suppose to uninstall it when we run `bash kind.sh --clean`

**Comment by eric978** [comment] 2022-07-22 11:50
Sure... I'd vote to (give the user the option to) install the tools.   Fwiw, I think there's an ansible script under the ec2 dir that installs the needed tools (in the case where you spin up an ec2 VM to run kind.sh in).   So could maybe leverage that?

**Comment by divya-mohan0209** [comment] 2022-07-24 11:11
Would you be willing to work on this @AvineshTripathi ?If you are, we can assign this issue to you.

**Comment by AvineshTripathi** [comment] 2022-07-24 14:14
yep I'll take this up

**Comment by AvineshTripathi** [comment] 2022-07-26 08:23
I have a question do we want to create a new host for ansible playbooks if so would we use the same file under `ec2/ansible/role/..` or we create a seperate role for `kind` folder
Anything I missed?

**Comment by eric978** [comment] 2022-07-27 12:01
If you're thinking to make an ansible playbook for kind.sh, I'd think to put it under the kind dir.   Seems like that'd make it more self-sufficient.

**Comment by AvineshTripathi** [comment] 2022-07-27 14:05
will that be the best solution to the problem statement?

**Comment by eric978** [comment] 2022-07-28 20:21
Seems reasonable to me.   The ec2 one was intended to get everything together for a newly launched vm (which may be the stuff kind.sh needs + more).  If you make kind.sh be self sufficient then the one under ec2 can probably get smaller and trust kind.sh to take care of itself.

**Comment by 26tanishabanik** [comment] 2022-08-18 06:58
Have all the pre-requisites been added in the kind.sh script for kubectl, docker, kubectx, helm and kind ?

**Comment by eric978** [comment] 2022-08-18 13:26
@AvineshTripathi has a PR that (afaik) adds them all?

**Comment by AvineshTripathi** [comment] 2022-08-18 13:50
Yes the PR linked adds all the prerequisite

if you see the script i.e. kind.sh you'll see a `ansible-playbook -i ......` that basically downloads all the pre.. mentioned in `main.yaml` present in the ansible directory.

Hope this answers your question

**Comment by 26tanishabanik** [comment] 2022-08-18 14:20
> Yes the PR linked adds all the prerequisite
> 
> if you see the script i.e. kind.sh you'll see a `ansible-playbook -i ......` that basically downloads all the pre.. mentioned in `main.yaml` present in the ansible directory.
> 
> Hope this answers your question

Okay, thanks for the info

**Closed** 2022-09-09 12:02 UTC
